apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
  nodePort: 30001  # Corrected capitalization to "nodePort"
